### ISSUE TITLE
Allgemeine Frage

### ISSUE THREAD

**Issue by jbleyel** [MDXDave/ModernWebif#14]
Hi David,

ich finde deinen Ansatz für eine bessere UI vom openwebif sehr gut.
ABER. Du hast einige Dinge nicht bedacht.
Du kannst dein Plugin und das openwebif nicht gleichzeitig auf einer Box benutzen.
Alle 3rd party Application werden mit deinem Plugin nicht richtig funktionieren.

Wieso machst du nicht einfach nur ein neues zusätzliches CSS (Theme) welches man über die Plugin Einstellungen auswählen kann.
Ich hab leider nicht viel Zeit, sonst hätte ich schon lange die altbackene UI auf bootstrap oder was ähnliches umgestellt.

Gruß
Jörg

**Comment by sgse** [comment]
Hi,
leider hat David das Projekt wohl auf gegeben. Seit dem 31.03.2016, 01:25 nichts mehr in Sachen Modern gehört. Meine Beiträge dazu wurden im Forum http://www.opena.tv/plugins/23381-modernwebif-themed-openwebif-post218828.html#post218828 versehentlich gelöscht.
Parallele Nutzung mit unterschiedlichen Ports (80 und 88) ist/war möglich. L4L ging nicht ohne OpenWebif. Heißt, beide installieren und alles geht :) .
Gruß
sgse aka sgs aka sgsduo :)

**Comment by jbleyel** [comment]
Danke für die Info.
Aber beide plugins auf der Box ist nicht wirklich zielführend.
Also dann doch Theme für openwebif.
Wenn ich mal VIEEEEL Zeit hab.

**Comment by sgse** [comment]
Dann drück ich mal die Daumen für mehr Zeit :)

Ja, nutze nur noch OpenWebif, Optik ist ja nicht hässlich. Hab es etwas aufgehübscht.

![git mdxdave atv1](https://cloud.githubusercontent.com/assets/17575778/19222519/c8b515f0-8e5a-11e6-8f72-ffc88395869c.png)
Will wohl keiner einbauen
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/369
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/368

![git mdxdave atv2](https://cloud.githubusercontent.com/assets/17575778/19222523/da30dc74-8e5a-11e6-855b-e6891fff1d74.png)

**Comment by jbleyel** [comment]
Ich hab mal angefangen:
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/tree/Theme

Ist noch nicht 100% perfekt.
Aber es ist deutlich einfacher.
Ich nutze die Themes von jQuery UI.
Das macht es viel einfacher.

**Comment by sgse** [comment]
Freut mich zu hören/lesen :) , leider bin ich die nächsten Tage offline, kann daher leider erst später dein Werk testen. Danke schon mal für deinen Einsatz :)

**Comment by sgse** [comment]
Habe nicht warten können aber meine generierte IPK zeigt noch keine Theme-Auswahl unter Extras.
Aufgefallen ist mir das Menü "Streame", ein e zu viel oder ein n zu wenig?

Freue mich schon auf die neuen Themes :) 

![stream](https://cloud.githubusercontent.com/assets/17575778/19309178/a6a0d578-9083-11e6-9e6e-4de1b827632d.png)

**Comment by jbleyel** [comment]
Stream ist nicht übersetzt im openwebif.
Die Theme Auswahl sollte aber gehen mit dem aktuellen Stand.
ggf. passt das was mit dem IPK nicht.
Oder du musst erst alle pyo und alle template pyc files löschen.

**Comment by sgse** [comment]
Klar aber da steht "Streame" und google sagt "meinten sie stream" ;)

So ich nerve jetzt nicht weiter und schau mal ob ich es hin bekomme :)

**Comment by MDXDave** [comment]
@sgse Hey, also ich habe das Projekt nicht wirklich aufgeben, ich hab nur selbst zur Zeit relativ viel zu tun, weshalb das nicht bei mir die höchste Priorität hat ;)

@jbleyel Generell war es ursprünglich meine Idee lediglich ein CSS basierendes Theme zu machen, allerdings ist die HTML-Struktur nicht wirklich optimal dafür gewesen, weshalb ich diese an einigen Stellen geändert habe. An sich wäre es natürlich wirklich viel besser wenn man das ganze rein CSS basierend gestaltet und das Theme dann in den Optionen ändern könnte. Dafür sollte man am Besten die Struktur des Themes verbessern, mit jQuery UI finde ich auch nicht so optimal.

**Comment by jbleyel** [comment]
Hi MDXDave,
ich hatte nicht vor die komplette Seite umzubauen, sondern nur die uralte jquery und jquery UI zu aktualisieren. Dabei sind auch gleich ein paar Fehler berichtigt worden. JQuery UI wird auf jeden Fall gebraucht. Ob man die Themes von jQuery UI nimmt oder nicht, das ist Geschmacksache. Die gibt's geschenkt.

Du kannst aber gerne dein Projekt einstellen und lieber in die original Version deine Verbesserungen einbauen.
Natürlich nur wenn du möchtest.

**Comment by sgse** [comment]
@MDXDave Schön von dir zu lesen. Ich hatte ja auch, leider hat David das Projekt **wohl** auf gegeben , geschrieben. Ein kleiner Satz bei opena.tv, nach meiner Nachfrage, hätte gereicht. Sechs Monate sind im Computerzeitalter eine Ewigkeit ;) .
